apiVersion: logstash.k8s.elastic.co/v1alpha1
kind: Logstash
metadata:
  name: logstash
spec:
  count: 1
  elasticsearchRefs:
    - clusterName: elasticsearch
      name: elasticsearch
      
  version: 8.8.1
  pipelines:
    - pipeline.id: main
      config.string: |
        input {
          beats {
            port => 5044
          }
        }
        filter{
          grok {
            add_field => [ "received_at", "%{@timestamp}" ]
          }
        }
        output {
          elasticsearch {
            hosts => [ "${ELASTICSEARCH_ES_HOSTS}" ]
            index => "logstash_vss_%{+YYYY.MM.dd}"
            user => "${ELASTICSEARCH_ES_USER}"
            password => "${ELASTICSEARCH_ES_PASSWORD}"
            cacert => "${ELASTICSEARCH_ES_SSL_CERTIFICATE_AUTHORITY}"
          }
        }
  # hosts => ["https://elasticsearch-es-http.logging.svc:9200"]
  services:
    - name: beats
      service:
        spec:
          type: NodePort
          ports:
            - port: 5044
              name: "filebeat"
              # protocol: TCP
              targetPort: 5044